### PR TITLE
rggu improvements

### PR DESCRIPTION
**Pull request by smoke-b**

### CODE REVIEW

**Comment by smoke-b** [comment]
Кажется, питон 2.6 и 3.3 он просто не может скачать, чтобы проверить. Я тогда их удалю из проверок?

**Comment by smoke-b** [comment]
Hi! Now all checks have passed

**Comment by alexanderpanchenko** [comment]
ok, merged. thanks.

**Comment by smoke-b** [comment]
Thanks you. The most significant is the ability to pass directly to the mystem.exe the path to the file with the text, without reading it before that outside. This gives a huge increase in speed for Windows, where, if you pass the read text as an argument to the analyze function, a separate call is made to mystem.exe for each line of text, and each time mystem.exe is reloaded.

**Pull request merged**
